[project]
name = "my-code-agent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "langchain[openai]>=1.1.0",
    "langchain-mcp-adapters>=0.1.14",
    "langgraph>=1.0.4",
    "pexpect>=4.9.0",
    "langgraph-cli[inmem]>=0.4.7",
]
